init project
z-sector/anti-bruteforce pull request #1
Opened 2023-09-16 13:55 UTC by z-sector

2023-09-17 02:25 UTC, dshemin requested changes

2023-09-17 02:25 UTC, dshemin commented on api/proto/api.proto
> +  rpc Reset(AuthCheckRequest) returns (google.protobuf.Empty) {}
Критично:

Не вижу метода для реализации сброса бакета:

> Сброс bucket
> Должен очистить bucket-ы соответствующие переданным login и ip.
> login
>ip

2023-09-17 02:25 UTC, dshemin commented on build/service/Dockerfile
> +FROM alpine:3.9
Совет:

Можно использовать scratch.

2023-09-17 02:25 UTC, dshemin commented on cmd/cli/cmd/reset.go
> +		if resetF == (resetFlags{}) {
Критично:

Не реализовано.

2023-09-17 02:25 UTC, dshemin commented on config/config.go
> +		panic(err)
Совет:

Для проекта - пойдёт, но советую не использовать паник в продакшен коде.

2023-09-17 02:25 UTC, dshemin commented on internal/delivery/grpc/handler.go
> +	ok, err := h.uc.CheckAuth(ctx, in)
Важно:

Мы прокидываем в нашу бизнес логику структуру сгенерённую по protobuf, которая является частью инфраструкутрной логики - это плохо.

2023-09-17 02:25 UTC, dshemin commented on internal/delivery/grpc/handler.go
> +	if err := h.uc.Reset(ctx, in); err != nil {
Важно:

Тут тоже прокидывание структуры из gRPC

2023-09-25 09:05 UTC, z-sector commented on build/service/Dockerfile
> +FROM alpine:3.9
DONE

2023-09-25 09:14 UTC, z-sector commented on config/config.go
> +		panic(err)
Поэтому я сделал две функции MustConfig и NewConfig, где MustConfig вызывается только в main функции. В стандартной либе такой паттерн тоже используется

2023-09-25 11:36 UTC, z-sector commented on api/proto/api.proto
> +  rpc Reset(AuthCheckRequest) returns (google.protobuf.Empty) {}
DONE

2023-09-25 11:37 UTC, z-sector commented on internal/delivery/grpc/handler.go
> +	ok, err := h.uc.CheckAuth(ctx, in)
DONE

2023-09-25 11:37 UTC, z-sector commented on internal/delivery/grpc/handler.go
> +	if err := h.uc.Reset(ctx, in); err != nil {
DONE

2023-09-25 12:19 UTC, z-sector commented on cmd/cli/cmd/reset.go
> +		if resetF == (resetFlags{}) {
DONE

2023-09-26 17:33 UTC, dshemin approved these changes

2023-09-27 07:09 UTC, merged